name: Deploy ASP.NET Core App

on:
    push:
      branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:        
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ secrets.GHCR_USERNAME }}
            password: ${{ secrets.GHCR_TOKEN }}

        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - name: Build the Docker image
          working-directory: src
          run: docker build . -t ghcr.io/${{ secrets.GHCR_USERNAME }}/asp-rest-demo:latest

        - name: Push the images to github packages
          run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/asp-rest-demo:latest
